//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoC.Security.Mvc.Views.Account
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc.Html;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc;
    using System.Web.Routing;
    using System.Collections;
    using System.Collections.Specialized;
    using System.ComponentModel.DataAnnotations;
    using System.Configuration;
    using System.Text;
    using System.Text.RegularExpressions;
    using System.Web.Caching;
    using System.Web.DynamicData;
    using System.Web.SessionState;
    using System.Web.Profile;
    using System.Web.UI.WebControls;
    using System.Web.UI.WebControls.WebParts;
    using System.Web.UI.HtmlControls;
    using System.Xml.Linq;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MvcRazorClassGenerator", "1.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/Register.cshtml")]
    public class Register_cshtml : System.Web.Mvc.WebViewPage<BoC.Security.Mvc.ViewModels.RegisterModel>
    {
#line hidden

        protected System.Web.HttpApplication ApplicationInstance
        {
            get
            {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        public override void Execute()
        {

WriteLiteral("\r\n\r\n");


  
    View.Title = "Register";
	Layout = "~/Views/Shared/_Layout.cshtml";


WriteLiteral("\r\n<h2>Create a New Account</h2>\r\n<p>\r\n    Use the form below to create a new acco" +
"unt. \r\n</p>\r\n<p>\r\n    Passwords are required to be a minimum of ");


                                         Write(View.PasswordLength);

WriteLiteral(" characters in length.\r\n</p>\r\ndoei\r\n");


 using (Html.BeginForm()) {
    
Write(Html.ValidationSummary(true, "Account creation was unsuccessful. Please correct the errors and try again."));

                                                                                                                

WriteLiteral("    <div>\r\n        <fieldset>\r\n            <legend>Account Information</legend>\r\n" +
"\r\n            <div class=\"editor-label\">\r\n                ");


           Write(Html.LabelFor(m => m.UserName));

WriteLiteral("\r\n            </div>\r\n            <div class=\"editor-field\">\r\n                ");


           Write(Html.TextBoxFor(m => m.UserName));

WriteLiteral("\r\n                ");


           Write(Html.ValidationMessageFor(m => m.UserName));

WriteLiteral("\r\n            </div>\r\n\r\n            <div class=\"editor-label\">\r\n                ");


           Write(Html.LabelFor(m => m.Email));

WriteLiteral("\r\n            </div>\r\n            <div class=\"editor-field\">\r\n                ");


           Write(Html.TextBoxFor(m => m.Email));

WriteLiteral("\r\n                ");


           Write(Html.ValidationMessageFor(m => m.Email));

WriteLiteral("\r\n            </div>\r\n\r\n            <div class=\"editor-label\">\r\n                ");


           Write(Html.LabelFor(m => m.Password));

WriteLiteral("\r\n            </div>\r\n            <div class=\"editor-field\">\r\n                ");


           Write(Html.PasswordFor(m => m.Password));

WriteLiteral("\r\n                ");


           Write(Html.ValidationMessageFor(m => m.Password));

WriteLiteral("\r\n            </div>\r\n\r\n            <div class=\"editor-label\">\r\n                ");


           Write(Html.LabelFor(m => m.ConfirmPassword));

WriteLiteral("\r\n            </div>\r\n            <div class=\"editor-field\">\r\n                ");


           Write(Html.PasswordFor(m => m.ConfirmPassword));

WriteLiteral("\r\n                ");


           Write(Html.ValidationMessageFor(m => m.ConfirmPassword));

WriteLiteral("\r\n            </div>\r\n\r\n            <p>\r\n                <input type=\"submit\" val" +
"ue=\"Register\" />\r\n            </p>\r\n        </fieldset>\r\n    </div>\r\n");


}


        }
    }
}
