cd Commons
nuget pack
cd ..
cd Commons.InversionOfControl.DryIoC
nuget pack
cd ..
cd Commons.InversionOfControl.Ninject
nuget pack
cd ..
cd Commons.InversionOfControl.SimpleInjector
nuget pack
cd ..
cd Commons.InversionOfControl.Unity
nuget pack
cd ..
cd Commons.Logging.Log4Net
nuget pack
cd ..
cd Commons.Logging.Sitecore
nuget pack
cd ..
cd Commons.Persistence.db4o
nuget pack
cd ..
cd Commons.Persistence.NHibernate
nuget pack
cd ..
cd Commons.Persistence.NoRM
nuget pack
cd ..
cd Commons.Persistence.Sitecore
nuget pack
cd ..
cd Commons.Persistence.UmbracoGlass
nuget pack
cd ..
cd Commons.Persistence.XPO
nuget pack
cd ..
cd Commons.Security
nuget pack
cd ..
cd Commons.Security.Mvc
nuget pack
cd ..
cd Commons.Security.NHibernate
nuget pack
cd ..
cd Commons.Sitecore.Mvc
nuget pack
cd ..
cd Commons.Web.Mvc
nuget pack
cd ..
