<%@ Page Language="C#" MasterPageFile="~/mainmaster.master" AutoEventWireup="true" CodeFile="ShowUser.aspx.cs" Inherits="tests_ShowUser" Title="Untitled Page" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" Runat="Server">
    <asp:DetailsView ID="DetailsView1" runat="server" 
        DefaultMode="Edit"
        DataSource="<%# this.MyUser %>"
        AutoGenerateInsertbutton="true"
        AutoGenerateEditbutton="true"
        AutoGenerateDeletebutton="true"
    >
    </asp:DetailsView>
</asp:Content>

